Add Streaming Support
AdRoll/zstd-erlang pull request #43
Opened 2023-09-12 22:13 UTC by raz-adroll

2023-09-19 07:21 UTC, tak30 requested changes
The changes LGTM but there are no tests.
@raz-adroll  Could you add tests? 
Thanks!

2023-09-20 07:08 UTC, pablocostass approved these changes

2023-09-20 07:13 UTC, tak30 approved these changes

2023-09-20 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdRoll/zstd-erlang?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/AdRoll/zstd-erlang?pullRequest=43) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: raz-adroll<br/>:x: tak30<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdRoll/zstd-erlang?pullRequest=43) it.</sub>

2023-09-20 16:53 UTC, dannykansas approved these changes

2023-09-20 17:10 UTC, merged